[package]
name = "axum_tutorial_project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# tokio
tokio = { version = "1", features = ["full"] }
# Axum 
axum = "0.6"

[dev-dependencies]
anyhow = "1.0"
httpc-test = "0.1.1"
